# Generated by Django 3.2.3 on 2021-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='41018114',
            fields=[
                ('cPhone', models.CharField(blank=True, default='', max_length=50)),
                ('cName', models.CharField(max_length=20)),
            ],
        ),
    ]
